### ISSUE TITLE
请求异常，错误提示：parsererror

### ISSUE THREAD

**Issue by aaziguang** [yeuxuan/ccproxy_kami#2]
1.3安装之后报错，
1.1的正常。
请求异常，错误提示：parsererror
这个怎么解决

**Comment by yeuxuan** [comment]
联系QQ487735913，描述问题



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年7月23日(周六) 凌晨4:06
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [yeuxuan/ccproxy_kami] 请求异常，错误提示：parsererror (Issue #2)




 
1.3安装之后报错，
 1.1的正常。
 请求异常，错误提示：parsererror
 这个怎么解决
