### ISSUE TITLE
关于1.5版本发现的一些问题反馈

### ISSUE THREAD

**Issue by PengTao520** [yeuxuan/ccproxy_kami#4]
[一花1.5BUG反馈.docx](https://github.com/yeuxuan/ccproxy_kami/files/9858167/1.5BUG.docx)

**Comment by PengTao520** [comment]
总结成一个文档了，望查阅！

**Comment by yeuxuan** [comment]
[一花1.5BUG反馈修复进度.docx](https://github.com/yeuxuan/ccproxy_kami/files/9894101/1.5BUG.docx)
